component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/FIGS/.*
- ./bin/PS/.*
- ./bin/lessons/.*
- ./bin/sandmark/.*
- ./bin/sandmark/analysis/.*
- ./bin/sandmark/analysis/callgraph/.*
- ./bin/sandmark/analysis/classhierarchy/.*
- ./bin/sandmark/analysis/controlflowgraph/.*
- ./bin/sandmark/analysis/defuse/.*
- ./bin/sandmark/analysis/dependencygraph/.*
- ./bin/sandmark/analysis/doc/.*
- ./bin/sandmark/analysis/initialized/.*
- ./bin/sandmark/analysis/interference/.*
- ./bin/sandmark/analysis/liveness/.*
- ./bin/sandmark/analysis/slicingtools/.*
- ./bin/sandmark/analysis/stacksimulator/.*
- ./bin/sandmark/birthmark/.*
- ./bin/sandmark/birthmark/fieldvalues/.*
- ./bin/sandmark/birthmark/inheritstruct/.*
- ./bin/sandmark/birthmark/methodcalls/.*
- ./bin/sandmark/birthmark/usedclasses/.*
- ./bin/sandmark/birthmark/util/.*
- ./bin/sandmark/birthmark/windows/.*
- ./bin/sandmark/birthmark/wpp/.*
- ./bin/sandmark/config/.*
- ./bin/sandmark/decompile/.*
- ./bin/sandmark/decompile/doc/.*
- ./bin/sandmark/diff/.*
- ./bin/sandmark/diff/classdiff/.*
- ./bin/sandmark/diff/doc/.*
- ./bin/sandmark/diff/methoddiff/.*
- ./bin/sandmark/eclipse/.*
- ./bin/sandmark/gui/.*
- ./bin/sandmark/gui/diff/.*
- ./bin/sandmark/gui/images/.*
- ./bin/sandmark/html/.*
- ./bin/sandmark/metric/.*
- ./bin/sandmark/newstatistics/.*
- ./bin/sandmark/newstatistics/doc/.*
- ./bin/sandmark/obfuscate/.*
- ./bin/sandmark/obfuscate/ArrayObfuscation/.*
- ./bin/sandmark/obfuscate/ArrayObfuscation/doc/.*
- ./bin/sandmark/obfuscate/addbogusfields/.*
- ./bin/sandmark/obfuscate/addbogusfields/doc/.*
- ./bin/sandmark/obfuscate/appendboguscode/.*
- ./bin/sandmark/obfuscate/appendboguscode/doc/.*
- ./bin/sandmark/obfuscate/blockmarker/.*
- ./bin/sandmark/obfuscate/blockmarker/doc/.*
- ./bin/sandmark/obfuscate/boguspredicates/.*
- ./bin/sandmark/obfuscate/boguspredicates/doc/.*
- ./bin/sandmark/obfuscate/boolsplitter/.*
- ./bin/sandmark/obfuscate/boolsplitter/doc/.*
- ./bin/sandmark/obfuscate/branchinsertion/.*
- ./bin/sandmark/obfuscate/branchinsertion/doc/.*
- ./bin/sandmark/obfuscate/buggycode/.*
- ./bin/sandmark/obfuscate/buggycode/doc/.*
- ./bin/sandmark/obfuscate/classsplitter/.*
- ./bin/sandmark/obfuscate/classsplitter/doc/.*
- ./bin/sandmark/obfuscate/classsplitter/testfiles/.*
- ./bin/sandmark/obfuscate/classsplitter/testfiles/TTT_op/.*
- ./bin/sandmark/obfuscate/classsplitter/testfiles/false_op/.*
- ./bin/sandmark/obfuscate/doc/.*
- ./bin/sandmark/obfuscate/dynamicinliner/.*
- ./bin/sandmark/obfuscate/dynamicinliner/doc/.*
- ./bin/sandmark/obfuscate/encryptclasses/.*
- ./bin/sandmark/obfuscate/encryptclasses/doc/.*
- ./bin/sandmark/obfuscate/exceptionbranches/.*
- ./bin/sandmark/obfuscate/exceptionbranches/doc/.*
- ./bin/sandmark/obfuscate/inliner/.*
- ./bin/sandmark/obfuscate/inliner/doc/.*
- ./bin/sandmark/obfuscate/insertopaquepred/.*
- ./bin/sandmark/obfuscate/insertopaquepred/doc/.*
- ./bin/sandmark/obfuscate/instructionordering/.*
- ./bin/sandmark/obfuscate/instructionordering/doc/.*
- ./bin/sandmark/obfuscate/interleavemethods/.*
- ./bin/sandmark/obfuscate/interleavemethods/doc/.*
- ./bin/sandmark/obfuscate/irreducibility/.*
- ./bin/sandmark/obfuscate/irreducibility/doc/.*
- ./bin/sandmark/obfuscate/localvar/.*
- ./bin/sandmark/obfuscate/localvar/doc/.*
- ./bin/sandmark/obfuscate/loop/.*
- ./bin/sandmark/obfuscate/loop/doc/.*
- ./bin/sandmark/obfuscate/methodmadness/.*
- ./bin/sandmark/obfuscate/methodmadness/doc/.*
- ./bin/sandmark/obfuscate/modifyifelse/.*
- ./bin/sandmark/obfuscate/modifyifelse/doc/.*
- ./bin/sandmark/obfuscate/nameoverloading/.*
- ./bin/sandmark/obfuscate/nameoverloading/doc/.*
- ./bin/sandmark/obfuscate/nodesplitter/.*
- ./bin/sandmark/obfuscate/nodesplitter/doc/.*
- ./bin/sandmark/obfuscate/objectify/.*
- ./bin/sandmark/obfuscate/objectify/doc/.*
- ./bin/sandmark/obfuscate/outliner/.*
- ./bin/sandmark/obfuscate/outliner/doc/.*
- ./bin/sandmark/obfuscate/paramalias/.*
- ./bin/sandmark/obfuscate/paramalias/doc/.*
- ./bin/sandmark/obfuscate/promotelocals/.*
- ./bin/sandmark/obfuscate/promotelocals/doc/.*
- ./bin/sandmark/obfuscate/renameidentifiers/.*
- ./bin/sandmark/obfuscate/renameidentifiers/doc/.*
- ./bin/sandmark/obfuscate/reorder/.*
- ./bin/sandmark/obfuscate/reorder/constantpool/.*
- ./bin/sandmark/obfuscate/reorder/constantpool/doc/.*
- ./bin/sandmark/obfuscate/scalarmerger/.*
- ./bin/sandmark/obfuscate/scalarmerger/doc/.*
- ./bin/sandmark/obfuscate/setfieldspublic/.*
- ./bin/sandmark/obfuscate/setfieldspublic/doc/.*
- ./bin/sandmark/obfuscate/stringencoder/.*
- ./bin/sandmark/obfuscate/stringencoder/doc/.*
- ./bin/sandmark/obfuscate/util/.*
- ./bin/sandmark/obfuscate/varsplitter/.*
- ./bin/sandmark/obfuscate/varsplitter/doc/.*
- ./bin/sandmark/optimise/.*
- ./bin/sandmark/optimise/bloat/.*
- ./bin/sandmark/optimise/bloat/doc/.*
- ./bin/sandmark/optimise/doc/.*
- ./bin/sandmark/program/.*
- ./bin/sandmark/program/doc/.*
- ./bin/sandmark/program/util/.*
- ./bin/sandmark/smash/.*
- ./bin/sandmark/util/.*
- ./bin/sandmark/util/classloading/.*
- ./bin/sandmark/util/classloading/doc/.*
- ./bin/sandmark/util/doc/.*
- ./bin/sandmark/util/exec/.*
- ./bin/sandmark/util/exec/doc/.*
- ./bin/sandmark/util/exprtree/.*
- ./bin/sandmark/util/graph/.*
- ./bin/sandmark/util/graph/graphview/.*
- ./bin/sandmark/util/javagen/.*
- ./bin/sandmark/util/javagen/doc/.*
- ./bin/sandmark/util/newexprtree/.*
- ./bin/sandmark/util/newexprtree/doc/.*
- ./bin/sandmark/util/newgraph/.*
- ./bin/sandmark/util/newgraph/codec/.*
- ./bin/sandmark/util/newgraph/doc/.*
- ./bin/sandmark/util/opaquepredicatelib/.*
- ./bin/sandmark/util/opaquepredicatelib/doc/.*
- ./bin/sandmark/util/outliner/.*
- ./bin/sandmark/util/primitivepromotion/.*
- ./bin/sandmark/util/splitint/.*
- ./bin/sandmark/util/splitint/doc/.*
- ./bin/sandmark/util/stealth/.*
- ./bin/sandmark/view/.*
- ./bin/sandmark/view/doc/.*
- ./bin/sandmark/visualize/.*
- ./bin/sandmark/visualize/heap/.*
- ./bin/sandmark/watermark/.*
- ./bin/sandmark/watermark/addmethfield/.*
- ./bin/sandmark/watermark/addmethfield/doc/.*
- ./bin/sandmark/watermark/arboit/.*
- ./bin/sandmark/watermark/arboit/doc/.*
- ./bin/sandmark/watermark/arboit/trace/.*
- ./bin/sandmark/watermark/assignlv/.*
- ./bin/sandmark/watermark/assignlv/doc/.*
- ./bin/sandmark/watermark/bogusexp/.*
- ./bin/sandmark/watermark/bogusexp/doc/.*
- ./bin/sandmark/watermark/bogusinitializer/.*
- ./bin/sandmark/watermark/bogusinitializer/doc/.*
- ./bin/sandmark/watermark/bogusswitch/.*
- ./bin/sandmark/watermark/bogusswitch/doc/.*
- ./bin/sandmark/watermark/constantstring/.*
- ./bin/sandmark/watermark/constantstring/doc/.*
- ./bin/sandmark/watermark/ct/.*
- ./bin/sandmark/watermark/ct/doc/.*
- ./bin/sandmark/watermark/ct/embed/.*
- ./bin/sandmark/watermark/ct/encode/.*
- ./bin/sandmark/watermark/ct/encode/ir/.*
- ./bin/sandmark/watermark/ct/encode/ir2ir/.*
- ./bin/sandmark/watermark/ct/encode/storage/.*
- ./bin/sandmark/watermark/ct/recognize/.*
- ./bin/sandmark/watermark/ct/trace/.*
- ./bin/sandmark/watermark/ct/trace/callforest/.*
- ./bin/sandmark/watermark/dm/.*
- ./bin/sandmark/watermark/dm/doc/.*
- ./bin/sandmark/watermark/doc/.*
- ./bin/sandmark/watermark/execpath/.*
- ./bin/sandmark/watermark/execpath/doc/.*
- ./bin/sandmark/watermark/gtw/.*
- ./bin/sandmark/watermark/gtw/doc/.*
- ./bin/sandmark/watermark/gtw/eigen/.*
- ./bin/sandmark/watermark/hattrick/.*
- ./bin/sandmark/watermark/hattrick/doc/.*
- ./bin/sandmark/watermark/mondenwmark/.*
- ./bin/sandmark/watermark/mondenwmark/doc/.*
- ./bin/sandmark/watermark/mondenwmark/tests/.*
- ./bin/sandmark/watermark/mondenwmark/tests/watermarked/.*
- ./bin/sandmark/watermark/objectwm/.*
- ./bin/sandmark/watermark/objectwm/doc/.*
- ./bin/sandmark/watermark/steganography/.*
- ./bin/sandmark/watermark/steganography/doc/.*
- ./bin/sandmark/watermark/util/.*
- ./bin/sandmark/wizard/.*
- ./bin/sandmark/wizard/decision/.*
- ./bin/sandmark/wizard/decision/priority/.*
- ./bin/sandmark/wizard/decision/random/.*
- ./bin/sandmark/wizard/evaluation/.*
- ./bin/sandmark/wizard/evaluation/hprof/.*
- ./bin/sandmark/wizard/evaluation/swmetric/.*
- ./bin/sandmark/wizard/executive/.*
- ./bin/sandmark/wizard/modeling/.*
- ./bin/sandmark/wizard/modeling/dfa/.*
- ./bin/sandmark/wizard/modeling/lazydfa/.*
- ./bin/sandmark/wizard/modeling/set/.*
- ./bin/sandmark/wizard/modeling/wmdag/.*
- ./bin/sandmark/wizard/quickprotect/.*
- ./bin/sandmark/wizard/quickprotect/doc/.*
- ./doc/.*
- ./doc/FIGS/.*
- ./doc/PS/.*
- ./junit/.*
- ./junit/sandmark/.*
- ./junit/sandmark/util/.*
- ./junit/sandmark/util/newgraph/.*
- ./junit/sandmark/util/newgraph/codec/.*
- ./lessons/.*
- ./lib/.*
- ./lib/bogusinitializer/.*
- ./lib/boguspredicates/.*
- ./lib/classsplitter/.*
- ./lib/classsplitter/testfiles/.*
- ./lib/mondenwmark/.*
- ./lib/mondenwmark/tests/.*
- ./lib/mondenwmark/tests/watermarked/.*
- ./lib/nodesplitter/.*
- ./lib/obfuscate/.*
- ./lib/obfuscate/boguspredicates/.*
- ./lib/obfuscate/classsplitter/.*
- ./lib/obfuscate/classsplitter/testfiles/.*
- ./lib/obfuscate/nodesplitter/.*
- ./lib/obfuscate/setfieldspublic/.*
- ./lib/setfieldspublic/.*
- ./lib/watermark/.*
- ./lib/watermark/bogusinitializer/.*
- ./lib/watermark/mondenwmark/.*
- ./lib/watermark/mondenwmark/tests/.*
- ./lib/watermark/mondenwmark/tests/watermarked/.*
